name: CI

on:
    pull_request:
    push:
        branches: [main]

permissions:
    contents: read

jobs:
    ci:
        name: Lint • Typecheck • Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Install
              run: npm ci

            # Step 1: Lint
            - name: Lint
              run: npm run ci:lint

            # Step 2: Typecheck
            - name: Typecheck
              run: npm run ci:typecheck

            # Step 3: Build
            - name: Build
              run: npm run ci:build

            # Optional: upload the build artifact for debugging
            - name: Upload build artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: next-build
                  path: |
                      .next
                      out
                  retention-days: 7
