name: Deploy (simple Docker over SSH)
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Deploy
              env:
                  SSH_HOST: ${{ secrets.VPS_HOST }}
                  SSH_USER: ${{ secrets.VPS_USER }}
                  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  REMOTE_DIR: ${{ secrets.VPS_UPLOAD_DIR }}
                  CONTAINER_NAME: algotrainer
                  LOCAL_PORT: '3000'
              run: bash scripts/deploy/deploy_docker_over_ssh.sh
